from homeassistant.const import Platform

DOMAIN = "redsea"

DEVICE_MANUFACTURER="Red Sea"

CONF_FLOW_PLATFORM = "platform"

PLATFORMS: list[Platform] = [Platform.LIGHT,Platform.SENSOR,Platform.BINARY_SENSOR,Platform.SWITCH]

CONFIG_FLOW_IP_ADDRESS="ip_address"
CONFIG_FLOW_HW_MODEL="hw_model"

SCAN_INTERVAL=120 #in seconds
DO_NOT_REFRESH_TIME=2 #in seconds

FAN_INTERNAL_NAME='fan'
TEMPERATURE_INTERNAL_NAME="temperature"
WHITE_INTERNAL_NAME="white"
BLUE_INTERNAL_NAME="blue"
MOON_INTERNAL_NAME="moon"
STATUS_INTERNAL_NAME="status"
IP_INTERNAL_NAME="ip"

#MAT SENSORS
MAT_TODAY_USAGE_INTERNAL_NAME="today_usage"
MAT_DAILY_AVERAGE_USAGE_INTERNAL_NAME="daily_average_usage"
MAT_TOTAL_USAGE_INTERNAL_NAME="total_usage"
MAT_REMAINING_LENGTH_INTERNAL_NAME="remaining_length"
MAT_DAYS_TILL_END_OF_ROLL_INTERNAL_NAME="days_till_end_of_roll"
MAT_SENSORS_INTERNAL_NAME=[MAT_TODAY_USAGE_INTERNAL_NAME,MAT_DAILY_AVERAGE_USAGE_INTERNAL_NAME,MAT_TOTAL_USAGE_INTERNAL_NAME,MAT_REMAINING_LENGTH_INTERNAL_NAME,MAT_DAYS_TILL_END_OF_ROLL_INTERNAL_NAME]
#MAT BINARY_SENSORS
MAT_UNCLEAN_SENSOR_INTERNAL_NAME="unclean_sensor"
MAT_AUTO_ADVANCE_INTERNAL_NAME="auto_advance"
MAT_BINARY_SENSORS_INTERNAL_NAME=[MAT_UNCLEAN_SENSOR_INTERNAL_NAME,MAT_AUTO_ADVANCE_INTERNAL_NAME]

#DOSE__INTERNAL_NAME
DOSE_SUPPLEMENT_INTERNAL_NAME="supplement"
DOSE_STATE_INTERNAL_NAME="state"
DOSE_AUTO_DOSED_TODAY_INTERNAL_NAME="auto_dosed_today"
DOSE_MANUAL_DOSED_TODAY_INTERNAL_NAME="manual_dosed_today"
DOSE_DOSES_TODAY_INTERNAL_NAME="doses_today"
DOSE_DAILY_DOSE_INTERNAL_NAME="daily_dose"
DOSE_REMAINING_DAYS_INTERNAL_NAME="remaining_days"
DOSE_STOCK_LEVEL_INTERNAL_NAME="stock_level"
DOSE_DAILY_DOSES_INTERNAL_NAME="daily_doses"

DOSE_MISSED_DOSE_MISSED_VOLUME_INTERNAL_NAME="missed_volume"
DOSE_MISSED_DOSE_TOTAL_VOLUME_INTERNAL_NAME="total_volume"
#
DOSE_SENSORS_INTERNAL_NAME=[
    DOSE_SUPPLEMENT_INTERNAL_NAME,
    DOSE_AUTO_DOSED_TODAY_INTERNAL_NAME,
    DOSE_MANUAL_DOSED_TODAY_INTERNAL_NAME,
    DOSE_DOSES_TODAY_INTERNAL_NAME,
    DOSE_DAILY_DOSE_INTERNAL_NAME,
    DOSE_REMAINING_DAYS_INTERNAL_NAME,
    DOSE_DAILY_DOSES_INTERNAL_NAME
]
DOSE_SENSORS_MISSED_INTERNAL_NAME=[DOSE_MISSED_DOSE_MISSED_VOLUME_INTERNAL_NAME,DOSE_MISSED_DOSE_TOTAL_VOLUME_INTERNAL_NAME]
#DOSE binary sensors
DOSE_RECALIBRATION_REQUIRED_INTERNAL_NAME="recalibration_required"

MODEL_NAME="hw_model"
MODEL_ID="hwid"
HW_VERSION="hw_revision"
SW_VERSION="version"

HW_LED_IDS=['RSLED160','RSLED90','RSLED50']
HW_DOSE_IDS=['RSDOSE4','RSDOSE2']
HW_MAT_IDS=['RSMAT']

DAILY_PROG_INTERNAL_NAME="daily_prog"

VIRTUAL_LED="virtual_led"
VIRTUAL_LED_INIT_DELAY=5 #wait 5s to be sure real LED have been configured
LINKED_LED="linked"

CONVERSION_COEF=100/255

