from homeassistant.const import Platform

DOMAIN = "redsea"

DEVICE_MANUFACTURER="Red Sea"

CONF_FLOW_PLATFORM = "platform"

PLATFORMS: list[Platform] = [Platform.LIGHT,Platform.SENSOR,Platform.BINARY_SENSOR,Platform.SWITCH,Platform.NUMBER,Platform.BUTTON]

CONFIG_FLOW_IP_ADDRESS="ip_address"
CONFIG_FLOW_HW_MODEL="hw_model"

SCAN_INTERVAL=120 #in seconds
DO_NOT_REFRESH_TIME=2 #in seconds

FAN_INTERNAL_NAME='fan'
TEMPERATURE_INTERNAL_NAME="temperature"
WHITE_INTERNAL_NAME="white"
BLUE_INTERNAL_NAME="blue"
MOON_INTERNAL_NAME="moon"
STATUS_INTERNAL_NAME="status"
IP_INTERNAL_NAME="ip"
 
################################################################################
#MAT SENSORS
MAT_TODAY_USAGE_INTERNAL_NAME="today_usage"
MAT_DAILY_AVERAGE_USAGE_INTERNAL_NAME="daily_average_usage"
MAT_TOTAL_USAGE_INTERNAL_NAME="total_usage"
MAT_REMAINING_LENGTH_INTERNAL_NAME="remaining_length"
MAT_DAYS_TILL_END_OF_ROLL_INTERNAL_NAME="days_till_end_of_roll"
MAT_SENSORS_INTERNAL_NAME=[MAT_TODAY_USAGE_INTERNAL_NAME,MAT_DAILY_AVERAGE_USAGE_INTERNAL_NAME,MAT_TOTAL_USAGE_INTERNAL_NAME,MAT_REMAINING_LENGTH_INTERNAL_NAME,MAT_DAYS_TILL_END_OF_ROLL_INTERNAL_NAME]
#MAT BINARY_SENSORS
MAT_UNCLEAN_SENSOR_INTERNAL_NAME="unclean_sensor"
MAT_IS_EC_SENSOR_CONNECTED_INTERNAL_NAME="is_ec_sensor_connected"
MAT_BINARY_SENSORS_INTERNAL_NAME=[MAT_UNCLEAN_SENSOR_INTERNAL_NAME,MAT_IS_EC_SENSOR_CONNECTED_INTERNAL_NAME]
#MAT SWITCHES
MAT_AUTO_ADVANCE_INTERNAL_NAME="auto_advance"
MAT_SWITCHES_INTERNAL_NAME=[MAT_AUTO_ADVANCE_INTERNAL_NAME]
#MAT NUMBERS
MAT_CUSTOM_ADVANCE_VALUE_INTERNAL_NAME="custom_advance_value"
MAT_NUMBERS_INTERNAL_NAME=[MAT_CUSTOM_ADVANCE_VALUE_INTERNAL_NAME]
########################################

#DOSE__INTERNAL_NAME
DOSE_SUPPLEMENT_INTERNAL_NAME="supplement"
DOSE_STATE_INTERNAL_NAME="state"
DOSE_AUTO_DOSED_TODAY_INTERNAL_NAME="auto_dosed_today"
DOSE_MANUAL_DOSED_TODAY_INTERNAL_NAME="manual_dosed_today"
DOSE_DOSES_TODAY_INTERNAL_NAME="doses_today"
DOSE_DAILY_DOSE_INTERNAL_NAME="daily_dose"
DOSE_REMAINING_DAYS_INTERNAL_NAME="remaining_days"
DOSE_STOCK_LEVEL_INTERNAL_NAME="stock_level"
DOSE_DAILY_DOSES_INTERNAL_NAME="daily_doses"

DOSE_MISSED_DOSE_MISSED_VOLUME_INTERNAL_NAME="missed_volume"
DOSE_MISSED_DOSE_TOTAL_VOLUME_INTERNAL_NAME="total_volume"
#
DOSE_SENSORS_INTERNAL_NAME=[
    DOSE_SUPPLEMENT_INTERNAL_NAME,
    DOSE_AUTO_DOSED_TODAY_INTERNAL_NAME,
    DOSE_MANUAL_DOSED_TODAY_INTERNAL_NAME,
    DOSE_DOSES_TODAY_INTERNAL_NAME,
    DOSE_DAILY_DOSE_INTERNAL_NAME,
    DOSE_REMAINING_DAYS_INTERNAL_NAME,
    DOSE_DAILY_DOSES_INTERNAL_NAME
]
DOSE_SENSORS_MISSED_INTERNAL_NAME=[DOSE_MISSED_DOSE_MISSED_VOLUME_INTERNAL_NAME,DOSE_MISSED_DOSE_TOTAL_VOLUME_INTERNAL_NAME]
#DOSE binary sensors
DOSE_RECALIBRATION_REQUIRED_INTERNAL_NAME="recalibration_required"

#DOSE NUMBERS
DOSE_MANUAL_HEAD_1_VOLUME_INTERNAL_NAME="manual_head_1_volume"
DOSE_MANUAL_HEAD_2_VOLUME_INTERNAL_NAME="manual_head_2_volume"
DOSE_MANUAL_HEAD_3_VOLUME_INTERNAL_NAME="manual_head_3_volume"
DOSE_MANUAL_HEAD_4_VOLUME_INTERNAL_NAME="manual_head_4_volume"


################################################################################
# ATO
#ATO_SENSORS
ATO_TODAY_FILLS_INTERNAL_NAME="today_fills"
ATO_TODAY_VOLUME_USAGE_INTERNAL_NAME="today_volume_usage"
ATO_TOTAL_VOLUME_USAGE_INTERNAL_NAME="total_volume_usage"
ATO_TOTAL_FILLS_INTERNAL_NAME="total_fills"
ATO_DAILY_FILLS_AVERAGE_INTERNAL_NAME="daily_fills_average"
ATO_DAILY_VOLUME_AVERAGE_INTERNAL_NAME="daily_volume_average"
ATO_VOLUME_LEFT_INTERNAL_NAME="volume_left"
ATO_DAYS_TILL_EMPTY_INTERNAL_NAME="days_till_empty"
ATO_WATER_LEVEL_INTERNAL_NAME="water_level"
ATO_IS_PUMP_ON_INTERNAL_NAME="is_pump_on"
ATO_BASE_SENSORS=[ATO_TODAY_FILLS_INTERNAL_NAME,ATO_TODAY_VOLUME_USAGE_INTERNAL_NAME,ATO_TOTAL_VOLUME_USAGE_INTERNAL_NAME,ATO_TOTAL_FILLS_INTERNAL_NAME,ATO_DAILY_FILLS_AVERAGE_INTERNAL_NAME,ATO_DAILY_VOLUME_AVERAGE_INTERNAL_NAME,ATO_VOLUME_LEFT_INTERNAL_NAME,ATO_WATER_LEVEL_INTERNAL_NAME,ATO_DAYS_TILL_EMPTY_INTERNAL_NAME]
ATO_BASE_BINARY_SENSORS=[ATO_IS_PUMP_ON_INTERNAL_NAME]
#SUB LEAK
ATO_LEAK_SENSOR_CONNECTED_INTERNAL_NAME="connected"
ATO_LEAK_SENSOR_ENABLED_INTERNAL_NAME="enabled"
ATO_LEAK_SENSOR_BUZZER_ENABLED_INTERNAL_NAME="buzzer_enabled"
ATO_LEAK_SENSOR_STATUS_INTERNAL_NAME="status"
ATO_LEAK_BINARY_SENSORS=[ATO_LEAK_SENSOR_CONNECTED_INTERNAL_NAME,ATO_LEAK_SENSOR_ENABLED_INTERNAL_NAME,ATO_LEAK_SENSOR_BUZZER_ENABLED_INTERNAL_NAME]
ATO_LEAK_SENSORS=[ATO_LEAK_SENSOR_STATUS_INTERNAL_NAME]

#SUB ATO
ATO_ATO_SENSOR_IS_SENSOR_ERROR_INTERNAL_NAME="is_sensor_error"
ATO_ATO_SENSOR_IS_TEMP_ENABLED_INTERNAL_NAME="is_temp_enabled"
ATO_ATO_SENSOR_CURRENT_LEVEL_INTERNAL_NAME="current_level"
ATO_ATO_SENSOR_CURRENT_READ_INTERNAL_NAME="current_read"
ATO_ATO_SENSOR_TEMPERATURE_PROBE_STATUS_INTERNAL_NAME="temperature_probe_status"
ATO_ATO_BINARY_SENSORS=[ATO_ATO_SENSOR_IS_SENSOR_ERROR_INTERNAL_NAME,ATO_ATO_SENSOR_IS_TEMP_ENABLED_INTERNAL_NAME]
ATO_ATO_SENSORS=[ATO_ATO_SENSOR_CURRENT_LEVEL_INTERNAL_NAME,ATO_ATO_SENSOR_CURRENT_READ_INTERNAL_NAME,ATO_ATO_SENSOR_TEMPERATURE_PROBE_STATUS_INTERNAL_NAME]

#MAT SWITCHES
ATO_AUTO_FILL_INTERNAL_NAME="auto_fill"
ATO_SWITCHES_INTERNAL_NAME=[ATO_AUTO_FILL_INTERNAL_NAME]

################################################################################

MODEL_NAME="hw_model"
MODEL_ID="hwid"
HW_VERSION="hw_revision"
SW_VERSION="version"

HW_LED_IDS=['RSLED160','RSLED90','RSLED50','RSLED115','RSLED60','RSLED175']
HW_DOSE_IDS=['RSDOSE4','RSDOSE2']
HW_MAT_IDS=['RSMAT','RSMAT500']
HW_ATO_IDS=['RSATO+']
HW_RUN_IDS=['RSRUN']
HW_WAVE_IDS=['RSWAVE45','RSWAVE25']

HW_DEVICES_IDS=HW_LED_IDS+HW_DOSE_IDS+HW_MAT_IDS+HW_RUN_IDS+HW_WAVE_IDS

DAILY_PROG_INTERNAL_NAME="daily_prog"

VIRTUAL_LED="virtual_led"
VIRTUAL_LED_INIT_DELAY=5 #wait 5s to be sure real LED have been configured
LINKED_LED="linked"

CONVERSION_COEF=100/255

