name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Set version number from trigger's tag"
        run: |
          yq -i -o json '.version="${{ github.ref_name }}"' \
            "${{ github.workspace }}/custom_components/redsea/manifest.json"
